copeinca/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from material.frontend import urls as frontend_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('despachos.urls', namespace='despachos')),
    url(r'', include(frontend_urls)),
]

despachos/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'despachos'
urlpatterns = [
    url(r'^$', views.principal, name="principal"),
    url(r'^login/$', views.login ,name='login'),
    url(r'^logout/$', views.logout,name='logout'),
    url(r'^servidor/$', views.servidor_list, name="servidor"),
    url(r'^servidor/new/$', views.servidor_new, name='servidor_new'),
    url(r'^servidor/edit/(?P<pk>[0-9]+)/$', views.servidor_edit, name='servidor_edit'),
    url(r'^projeto/$', views.projeto_list, name="projeto"),
    url(r'^projeto/new/$', views.projeto_new, name='projeto_new'),
    url(r'^projeto/edit/(?P<pk>[0-9]+)/$', views.projeto_edit, name='projeto_edit'),
    url(r'^bolsista/$', views.bolsista_list, name="bolsista"),
    url(r'^bolsista/new/$', views.bolsista_new, name='bolsista_new'),
    url(r'^despacho_processo/$', views.despacho_processo_list, name='despacho_processo'),
    url(r'^despacho_processo/new/$', views.despacho_processo_new, name='despacho_processo_new'),
    url(r'^despacho_processo/edit/(?P<pk>[0-9]{5}.[0-9]{6}.[0-9]{4}-[0-9]{2})/$', views.despacho_processo_edit, name='despacho_processo_edit'),
    url(r'^despacho_processo/delete/(?P<pk>[0-9]{5}.[0-9]{6}.[0-9]{4}-[0-9]{2})/$', views.despacho_processo_delete, name='despacho_processo_delete'),
    url(r'^despacho_processo/print/(?P<pk>[0-9]{5}.[0-9]{6}.[0-9]{4}-[0-9]{2})/$', views.despacho_processo_print, name='despacho_processo_print'),
    url(r'^pagamentos/(?P<projeto>[0-9]+)/$', views.pagamentos, name='pagamentos'),
    url(r'^planejamento/$', views.planejamento_list, name='planejamento'),
    url(r'^orcamento/$', views.orcamento_list, name='orcamento'),
    url(r'^orcamento/new/$', views.orcamento_new, name='orcamento_new'),
    url(r'^planejamento/new/$', views.planejamento_new, name='planejamento_new'),
    url(r'^cotacao/$', views.cotacao_list, name="cotacao"),
    url(r'^cotacao/new/$', views.cotacao_new, name='cotacao_new'),
    url(r'^cotacao/edit/(?P<pk>[0-9]+)/$', views.cotacao_edit, name='cotacao_edit'),
    url(r'^planejamento/show/(?P<pk>[0-9]+)/$', views.planejamento_show, name='planejamento_show'),

    #url(r'^planejamento_semestre/$', views.planejamento_semetre, name='planejamento_semestre'),

    #url(r'^/$', views.index, name='index'),


#    url(r'^pcd/(?P<pk>[0-9]+)/$', views.sync_pcd, name='sync_pcd'),
]

despachos/forms.py
from django import forms
from .models import Servidor
from .models import Projeto
from .models import Banco
from .models import Bolsista
from .models import DespachoProcesso
from .models import Edital
from .models import Planejamento,Orcamento,CotacaoDolar
from .choices import *
from django.forms.extras.widgets import SelectDateWidget
from django.utils import formats
from material import Layout, Row, Column,Span6
import datetime
from datetime import date
from material import Layout, Row, Column, Fieldset, Span2, Span3, Span5, Span6, Span10,Span12
from djmoney.forms import MoneyField


class ServidorForm(forms.ModelForm):
    class Meta:
        model = Servidor
        fields = ('siape', 'nome','email',)

class ProjetoForm(forms.ModelForm):

    coordenador = forms.ModelChoiceField(queryset=Servidor.objects.all(),widget=forms.Select)
    data_inicio = forms.DateField()
    data_fim = forms.DateField()
    finalizado = forms.NullBooleanField()

    class Meta:
        model = Projeto
        fields = ('coordenador', 'projeto','data_inicio', 'data_fim','finalizado',)


class BolsistaForm(forms.ModelForm):
    projeto = forms.ModelChoiceField(queryset=Projeto.objects.all(),widget=forms.Select)
    banco = forms.ModelChoiceField(queryset=Banco.objects.order_by('codigo'),widget=forms.Select)

    class Meta:
        model = Bolsista
        fields = ('projeto', 'banco','agencia','conta','operacao','nome','cpf','valor',)


class DespachoProcessoForm(forms.ModelForm):
    projeto = forms.ModelChoiceField(queryset=Projeto.objects.filter(finalizado = False),widget=forms.Select)
    solicitante = forms.ModelChoiceField(queryset=Servidor.objects.filter(siape__in = Projeto.objects.all().values_list('coordenador',flat = True)).order_by('nome'),widget=forms.Select)
    edital = forms.ModelChoiceField(queryset=Edital.objects.order_by('numero','ano'),widget=forms.Select)
    data_processo = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    data_despacho = forms.DateField(widget=forms.DateInput(attrs={'type':'date','value': formats.date_format(date.today(), "d/m/Y"), 'class':'datepicker'})  )
    periodo_bolsa_inicio = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    periodo_bolsa_fim = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    processo = forms.CharField()

    class Meta:
        model = DespachoProcesso

        fields = ('edital','projeto','processo', 'solicitante', 'data_processo', 'periodo_bolsa_inicio','periodo_bolsa_fim' ,'data_despacho',)


class LoginForm(forms.Form):
    username  = forms.CharField()
    password  = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ('username', 'password',)

class OrcamentoForm(forms.ModelForm):
    ano=forms.ChoiceField(choices=YEAR_CHOICES,widget=forms.Select(),required=True)
    semestre=forms.ChoiceField(choices = SEMESTRE_CHOICES,widget=forms.Select(),required=True)
    orcamento = MoneyField(default_currency='BRL')
    inicio=forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    fim=forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    class Meta:
        model = Orcamento
        fields = ("ano","semestre","orcamento","inicio","fim",)

class PlanejamentoForm(forms.ModelForm):
    projetos = forms.ChoiceField(choices=BOOL_CHOICES, widget=forms.Select(),required=True)
    estudando = forms.ChoiceField(choices=BOOL_CHOICES, widget=forms.Select(),required=True)
    numero_eventos_brasil = forms.IntegerField()
    numero_eventos_exterior = forms.IntegerField()
    titulacao = forms.ChoiceField(choices=TITULACAO_CHOICES, widget=forms.Select(),required=True)
    ingresso_ifrn = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    nome_evento = forms.CharField()
    justificativa_eventos = forms.CharField(widget=forms.TextInput)
    data_inicio_evento = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    data_fim_evento = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'datepicker'}) )
    prioridade_evento = forms.IntegerField()
    tipo_evento_capacitacao = forms.ChoiceField(choices=EVENTOS_CHOICES,widget=forms.Select(),required=True)
    semestre = forms.ModelChoiceField(queryset=Orcamento.objects.filter(inicio__lte=datetime.datetime.now(), fim__gte=datetime.datetime.now()),widget=forms.Select())
    relevancia = forms.ChoiceField(choices=BOOL_CHOICES, widget=forms.Select(),required=True)
    local_evento = forms.ChoiceField(choices=LOCAL_CHOICES, widget=forms.Select(),required=True)

    class Meta:
        model = Planejamento
        fields = ('prioridade_evento','nome_evento','justificativa_eventos','data_inicio_evento','data_fim_evento','local_evento','tipo_evento_capacitacao', 'semestre',  'relevancia','projetos','estudando','numero_eventos_brasil', 'numero_eventos_exterior', 'titulacao','ingresso_ifrn',)

class CotacaoForm(forms.ModelForm):
    valor = MoneyField(default_currency='BRL')

    class Meta:
        model = CotacaoDolar
        fields = ('valor',)

despachos/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
#from django.sessions import sessions

from .models import Servidor,Projeto,Bolsista,DespachoProcesso,Planejamento, Orcamento,CotacaoDolar

from .forms import ServidorForm
from .forms import ProjetoForm
from .forms import BolsistaForm
from .forms import DespachoProcessoForm
from .forms import LoginForm
from .forms import OrcamentoForm,PlanejamentoForm,CotacaoForm
from . import services
#from .print import DespachoPrint
from django.contrib.auth.decorators import login_required
from io import BytesIO
# Create your views here.

from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.models import User

from django import template
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist



@login_required(login_url='despachos:login')
def principal(request):
    return render(request, 'despachos/principal.html')

def logout(request):
    auth_logout(request)
    return redirect('/')

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST or None)
        if form.is_valid():
            form.username = request.POST['username']
            form.password = request.POST['password']
            if services.loginSUAP(form.username,form.password) is not None:
                user = authenticate(request=request,username=form.username, password=form.password)
                if user is not None:
                    auth_login(request, user)
                    return redirect('/')
                else:
                    try:
                        user = User.objects.get(username = form.username)
                        if not user is None:
                            user.set_password(form.password)
                            user.save()
                    except ObjectDoesNotExist:
                        user = User.objects.create_user(username = form.username, password = form.password)
                    user = authenticate(request=request,username=form.username, password=form.password)
                    if user is not None:
                        auth_login(request, user)
                        return redirect('/')

            else:
                return redirect('/')
    form = LoginForm()
    return render(request, 'despachos/login.html', { 'form': form })


@login_required(login_url='despachos:login')
def servidor_list(request):
    servidores = Servidor.objects.all()
    paginator = Paginator(servidores, 20) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        servidores = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        servidores = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        servidores = paginator.page(paginator.num_pages)

    return render(request, 'despachos/servidor_list.html', {'servidores':servidores})

@login_required(login_url='despachos:login')
def servidor_new(request):
    if(request.method == "POST"):
        form = ServidorForm(request.POST)
        if form.is_valid():
            servidor  = form.save(commit=False)
            servidor.save()
            return redirect('/servidor')
    else:
        form = ServidorForm()
    return render(request, 'despachos/servidor_form.html',{'form': form})

@login_required(login_url='despachos:login')
def servidor_edit(request,pk):
    servidor = get_object_or_404(Servidor, pk=pk)
    if(request.method == "POST"):
        form = ServidorForm(request.POST, instance = servidor)
        if form.is_valid():
            servidor = form.save(commit=False)
            servidor.save()
            return redirect('/servidor')
    else:
        form = ServidorForm(instance=servidor)
    return render(request, 'despachos/servidor_form.html',{'form': form})

@login_required(login_url='despachos:login')
def projeto_list(request):
    projetos = Projeto.objects.all()
    paginator = Paginator(projetos, 20) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        projetos = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        projetos = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        projetos = paginator.page(paginator.num_pages)

    return render(request, 'despachos/projeto_list.html', {'projetos':projetos})

@login_required(login_url='despachos:login')
def projeto_new(request):
    if(request.method == "POST"):
        form = ProjetoForm(request.POST)
        if form.is_valid():
            projeto = form.save(commit=False)
            projeto.save()
            return redirect('/projeto')
    else:
        form = ProjetoForm()
    return render(request, 'despachos/projeto_form.html',{'form': form})

@login_required(login_url='despachos:login')
def bolsista_list(request):
    bolsistas = Bolsista.objects.order_by('projeto','valor')
    paginator = Paginator(bolsistas, 20) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        bolsistas = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        bolsistas = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        bolsistas = paginator.page(paginator.num_pages)

    return render(request, 'despachos/bolsista_list.html', {'bolsistas':bolsistas})

@login_required(login_url='despachos:login')
def bolsista_new(request):
    if(request.method == "POST"):
        form = BolsistaForm(request.POST)
        if form.is_valid():
            bolsista = form.save(commit=False)
            bolsista.save()
            return redirect('/bolsista')
    else:
        form = BolsistaForm()
    return render(request, 'despachos/bolsista_form.html',{'form': form})

@login_required(login_url='despachos:login')
def despacho_processo_list(request):
    ds = DespachoProcesso.objects.order_by('-data_despacho')
    paginator = Paginator(ds, 5) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        ds = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        ds = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        ds = paginator.page(paginator.num_pages)

    return render(request, 'despachos/despacho_processo_list.html', {'ds':ds})

@login_required(login_url='despachos:login')
def despacho_processo_new(request):
    #despacho = get_object_or_404(DespachoProcesso, pk=pk)
    if(request.method == "POST"):
        form = DespachoProcessoForm(request.POST)
        if form.is_valid():
            despacho = form.save(commit=False)
            despacho.save()
            return redirect('/despacho_processo')
    else:
        form = DespachoProcessoForm()
    return render(request, 'despachos/despacho_processo_form.html',{'form': form})

@login_required(login_url='despachos:login')
def despacho_processo_delete(request, pk):
    obj = DespachoProcesso.objects.get(pk=pk)
    obj.delete()
    return redirect('/despacho_processo')

@login_required(login_url='despachos:login')
def despacho_processo_print(request, pk):
    obj = DespachoProcesso.objects.get(pk=pk)
    bolsistas = Bolsista.objects.filter(projeto = obj.projeto)

    return render(request,'despachos/despacho_processo_view.html',{'d':obj , 'bolsistas':bolsistas})

@login_required(login_url='despachos:login')
def despacho_processo_edit(request,pk):
    despacho = get_object_or_404(DespachoProcesso, pk=pk)
    if(request.method == "POST"):
        form = DespachoProcessoForm(request.POST, instance = despacho)
        if form.is_valid():
            despacho = form.save(commit=False)
            despacho.save()
            return redirect('/despacho_processo')
    else:
        form = DespachoProcessoForm(instance=despacho)
    return render(request, 'despachos/despacho_processo_form.html',{'form': form})

@login_required(login_url='despachos:login')
def pagamentos(request,projeto):
    despachos = DespachoProcesso.objects.filter(projeto = projeto)
    paginator = Paginator(despachos, 10) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        despachos = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        despachos = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        despachos = paginator.page(paginator.num_pages)


    return render(request, 'despachos/pagamentos_list.html',{'despachos': despachos})

@login_required(login_url='despachos:login')
def projeto_edit(request,pk):
    projeto = get_object_or_404(Projeto, pk=pk)
    if(request.method == "POST"):
        form = ProjetoForm(request.POST, instance = projeto)
        if form.is_valid():
            projeto = form.save(commit=False)
            projeto.save()
            return redirect('/projeto')
    else:
        form = ProjetoForm(instance=projeto)
    return render(request, 'despachos/projeto_form.html',{'form': form})

@login_required(login_url='despachos:login')
def planejamento_list(request):
    pls = Planejamento.objects.all()
    print(pls)
    if not request.user.is_superuser:
        pls = Planejamento.objects.filter(servidor=request.user)

    paginator = Paginator(pls, 20) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        pls = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        pls = paginator.page(1)
    except EmptyPage:

despachos/templates/despachos/bolsista_form.html
{% extends 'despachos/base.html' %}

{% block content %}
    <h1>Novo Bolsista</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
{% endblock %}

despachos/templates/despachos/bolsista_list.html
{% extends 'despachos/base.html' %}
{% block content %}
<table class="responsive-table striped">
   <thead>
     <tr>
         <th data-field="siape">Bolsista</th>
         <th data-field="nome">Projeto</th>
         <th data-field="email">CPF</th>
         <th data-field="email">Valor</th>

         <th data-field="email">Ações</th>

     </tr>
   </thead>
   <tbody>
    {% for u in bolsistas %}
      <tr>
         <td>{{u.nome}}</td>
         <td>{{u.projeto}}</td>
         <td>{{u.cpf}}</td>
         <td>R$ {{u.valor}},00</td>
         <td></td>

         </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if bolsistas.has_previous %}
            <a href="?page={{ bolsistas.previous_page_number }}"> << </a>
        {% endif %}

        <span class="current">
            Página {{ bolsistas.number }} de {{ bolsistas.paginator.num_pages }}.
        </span>

        {% if bolsistas.has_next %}
            <a href="?page={{ bolsistas.next_page_number }}"> >> </a>
        {% endif %}
    </span>
</div>
    <a href="{% url 'despachos:bolsista_new' %}" class="top-menu">Cadastrar Novo Bolsista</a>
{% endblock content %}

despachos/templates/despachos/cotacao_form.html
{% extends 'despachos/base.html' %}

{% block content %}
    <h1>Nova Cotação</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
{% endblock %}

despachos/templates/despachos/cotacao_list.html
{% extends 'despachos/base.html' %}
{% block content %}
<table class="responsive-table striped">
   <thead>
     <tr>
         <th data-field="siape">Cotacao</th>
         <th data-field="email">Ações</th>

     </tr>
   </thead>
   <tbody>
    {% for u in cotacoes %}
      <tr>
         <td>$1 equivale a {{u.valor}}</td>
         <td>
           <a href="{% url 'despachos:cotacao_edit' pk=u.id %}" class="top-menu">Editar</a>

         </td>

         </tr>
    {% endfor %}
  </tbody>
</table>

    <a href="{% url 'despachos:cotacao_new' %}" class="top-menu">Cadastrar Nova Cotacao</a>
{% endblock content %}

despachos/templates/despachos/despacho_processo_list.html
{% extends 'despachos/base.html' %}
{% block content %}
<h4>    <a href="{% url 'despachos:despacho_processo_new' %}" class="top-menu">Cadastrar Novo Despacho</a>
</h4>
<table class="responsive-table striped">
   <thead>
     <tr>
         <th data-field="processo">Processo</th>
         <th data-field="servidor">Solicitante</th>
         <th data-field="projeto">Projeto</th>
         <th data-field="data">Data</th>

         <th data-field="acoes">Ações</th>

     </tr>
   </thead>
   <tbody>
    {% for u in ds %}
      <tr>
         <td>{{u.processo}}</td>
         <td>{{u.solicitante}}</td>
         <td>{{u.projeto}}</td>
         <td>{{u.data_despacho}}</td>
         <td>
           <a href="{% url 'despachos:despacho_processo_edit' pk=u.pk %}"> <i class="small material-icons">mode_edit</i> </a>
           <a href="{% url 'despachos:despacho_processo_delete' pk=u.pk %}"> <i class="small material-icons">delete</i> </a>
           <a href="{% url 'despachos:despacho_processo_print' pk=u.pk %}"> <i class="small material-icons">print</i> </a>
         </td>

         </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if ds.has_previous %}
            <a href="?page={{ ds.previous_page_number }}"> << </a>
        {% endif %}

        <span class="current">
            Página {{ ds.number }} de {{ ds.paginator.num_pages }}.
        </span>

        {% if ds.has_next %}
            <a href="?page={{ ds.next_page_number }}"> >> </a>
        {% endif %}
    </span>
</div>

{% endblock content %}

despachos/templates/despachos/despacho_processo_view.html
{% load staticfiles %}
<html>
<head>
  <!--Import materialize.css-->
  <link href="{% static 'css/despacho.css' %}" rel="stylesheet" type="text/css"/>
  <title> Despacho Processo {{d.processo}} </title>
</head>
<body>
  <div class='logo'>

  </div>
  <div class="citalico">
    Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte     </div>

    <div class="citalico">     Campus Caicó    </div>

      <div class="citalico">        Coordenação de Pesquisa e Inovação

      </div>

<div class="despacho">
<p>  DESPACHO</p>
    Documento de Referência: Processo nº <b> {{d.processo}} </b>, de {{d.data_processo}}.

</div>

<div class="texto">
  Á DG:
</div>

<div class="texto">

<p>Recebidos os autos do processo identificado acima, do servidor <b>{{d.solicitante.nome}}</b>, encaminhado a esta Coordenação de Pesquisa, que trata da solicitação de pagamento de bolsa a
  servidor e/ou aluno bolsista, membro(s) de Projeto de Pesquisa, intitulado  <i><b> {{d.projeto.projeto}}</b></i>, contemplados com bolsa dentro do Programa de Apoio Institucional à Pesquisa, conforme seleção realizada segundo critérios constantes no Edital nº  <b>{{d.edital.numero}}/{{d.edital.ano}}–{{d.edital.setor}}/IFRN </b>, verificou-se que, no período de  <b>{{d.periodo_bolsa_inicio}} a {{d.periodo_bolsa_fim}}  </b>
   a carga horária do(s) bolsista(s) foi cumprida em conformidade com o estabelecido no referido Edital, bem como o relatório de atividades registrado no SUAP está satisfatório, o qual segue anexo para apreciação.
Solicitamos, portanto, que após análise, seja encaminhado COFINC/CA para providências.</p>
<p> Seguem abaixo os dados para pagamento:</p>

</div>
<div>
  <table>
    {% for u in bolsistas %}
      <tr>
        <td colspan="2"> Nome: {{u.nome}}</td>
        <td colspan="2"> CPF: {{u.cpf}} </td>
      </tr>
      <tr>
        <td> Banco: {{u.banco}}</td>
        <td> Agencia: {{u.agencia}} </td>
        <td> Conta: {{u.conta}}
            {% if u.operacao != "0" %}
              OP({{u.operacao}})
            {% endif %}
        </td>
        <td> Valor: R$ {{u.valor}},00 </td>

      </tr>
    {% endfor %}
  </table>
</div>


<div class="despacho">
<p>  Caicó,{{d.data_despacho}} </p>


</div>
    </body>
    </html>

despachos/templates/despachos/login.html
{% extends 'despachos/base.html' %}

{% block content %}
    <h1>LOGIN</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Login</button>
        <button type="reset" class="save btn btn-default">Reset</button>

    </form>
{% endblock %}

despachos/templates/despachos/orcamento_form.html
{% extends 'despachos/base.html' %}

{% block content %}
    <h1>Novo Orçamento</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
{% endblock %}

despachos/templates/despachos/planejamento_form.html
{% extends 'despachos/base.html' %}

{% block content %}
    <h1>Novo PLanejamento</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
{% endblock %}

despachos/templates/despachos/projeto_form.html
{% extends 'despachos/base.html' %}

{% block content %}
    <h1>Novo Projeto</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
{% endblock %}

despachos/templates/despachos/projeto_list.html
{% extends 'despachos/base.html' %}
{% block content %}
<table class="responsive-table striped">
   <thead>
     <tr>
         <th data-field="siape">Coordenador</th>
         <th data-field="nome">Projeto</th>
         <th data-field="inicio">Data de Início</th>
         <th data-field="fim">Data de Fim</th>

         <th data-field="acoes">Ações</th>

     </tr>
   </thead>
   <tbody>
    {% for u in projetos %}
      <tr>
         <td>{{u.coordenador}}</td>
         <td>{{u.projeto}}</td>
         <td>{{u.data_inicio}}</td>
         <td>{{u.data_fim}}</td>
         <td>  <a href="{% url 'despachos:pagamentos' projeto=u.pk %}" class="top-menu">Pagamentos</a>
            <a href="{% url 'despachos:projeto_edit' pk=u.pk %}" class="top-menu">Editar</a>

         </td>

         </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if projetos.has_previous %}
            <a href="?page={{ projetos.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ projetos.number }} of {{ projetos.paginator.num_pages }}.
        </span>

        {% if projetos.has_next %}
            <a href="?page={{ projetos.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
    <a href="{% url 'despachos:projeto_new' %}" class="top-menu">Cadastrar novo Projeto</a>
{% endblock content %}

despachos/templates/despachos/servidor_form.html
{% extends 'despachos/base.html' %}

{% block content %}
    <h1>Nova Servidor</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
{% endblock %}